# Use the official Node.js image as the base image
FROM node:14

# Set the working directory in the container to /usr/src/app
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the dependencies specified in the package.json file
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Specify the command to run your application
CMD [ "npm", "start" ]

# Expose port 3000 to allow traffic to the container
EXPOSE 3000
